[workspace]
resolver = "2"
members = [
    "model",
    "client/web",
    "server/zone",
    "server/world",
    "server/universe",
    "common/server",
    "common/network",
    "common/rust",
    "behavior",
]
